### ISSUE TITLE
Feedback JS EXAM

### ISSUE THREAD

**Issue by AndriiLitvin** [MarinaKam/MarinaKam.github.io#9]
1) структура файлов не совсем правильная. Хороший тон использовать такую как в [этой статье ](https://habrahabr.ru/post/250569/)
2) Все внешние скрипты конкатынируються минифицируються и подключаются отдельно например файл vendor.min.js( это не касается скриптов IE), твои скрипты подключаются отдельно 
3)БЭМ у тебя не совсем БЭМ  там [Пространство имен, заданное именем блока, определяет принадлежность элемента к данному блоку. Имя элемента отделяется от имени блока двумя подчеркиваниями (__).](https://ru.bem.info/method/naming-convention/) а у тебя одно и напутано.
4) при каждой загрузке страницы в плитке рамдомные картинки пункт 15 в ТЗ
5) на макете на плитке на каждой картинке полупрозрачный темный фон, сделать чтоб по ховеру он пропадал и при клике на картинку она высвечивалась в попапе(не обязательно но желательно).
6) поправь в ИЕ8
![image](https://cloud.githubusercontent.com/assets/13675947/14178698/706cfb34-f764-11e5-9e8a-19e7cb3968f6.png)
![image](https://cloud.githubusercontent.com/assets/13675947/14179137/9214d9ee-f766-11e5-993d-0cdcf27910c1.png)

7) 
![image](https://cloud.githubusercontent.com/assets/13675947/14178998/f318da70-f765-11e5-8fd0-d8bb1940cd30.png)
если спрайты делаешь круглыми то и картинки тоже нужно круглыми так как на ие не очень смотрится

**Comment by MarinaKam** [comment]
Исправила

**Comment by AndriiLitvin** [comment]
Зачет
